url: https://ColeEisenberg.github.io
baseurl: #

# Site settings
title: Cole Eisenberg's Website
email: cole.eisenberg@icloud.com
description: "A exemplerary mechanical engineering grad looking to earn his keep. They don't come more hard-working and motivated than this one"


# Team names, titles and social links
people:
- name: This is Me!
  pic: 1
  position: Mechanical Engineer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/coleeisenberg/
    - title: facebook
      url: #
    - title: instagram
      url: https://www.instagram.com/probably_not_cole/

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty