url: https://ColeEisenberg.github.io
baseurl: #

# Site settings
title: Cole Eisenberg's Website
email: cole.eisenberg@icloud.com
description: "A exemplerary mechanical engineering grad looking to earn his keep. They don't come more hard-working and motivated than this one!"


# Team names, titles and social links
people:
- name: This is Me!
  pic: 1
  position: Mechanical Engineer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/coleeisenberg/
    - title: instagram
      url: https://www.instagram.com/probably_not_cole/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/ColeEisenberg/ColeEisenberg.github.io
  - title: linkedin
    url: https://www.linkedin.com/in/coleeisenberg/
  - title: instagram
    url: https://www.instagram.com/probably_not_cole/


# Postal address (add as many lines as necessary)
address:
  - line: 84 Colgate Rd
  - line: East Jewett, NY 12424

# Build settings
markdown: kramdown
permalink: pretty